//
//  ArticlesPresenter.swift
//  RSSReader
//
//  Created Олег Крылов on 03/08/2019.
//  Copyright © 2019 OlegKrylov. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol ArticlesViewProtocol: class {

}

// MARK: Presenter -
protocol ArticlesPresenterProtocol: class {
	var view: ArticlesViewProtocol? { get set }
    func viewDidLoad()
}

class ArticlesPresenter: ArticlesPresenterProtocol {

    weak var view: ArticlesViewProtocol?

    func viewDidLoad() {

    }
}
