//
//  ArticlesViewController.swift
//  RSSReader
//
//  Created Олег Крылов on 03/08/2019.
//  Copyright © 2019 OlegKrylov. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class ArticlesViewController: UIViewController, ArticlesViewProtocol {

	var presenter: ArticlesPresenterProtocol

	init(presenter: ArticlesPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "ArticlesViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()

        presenter.view = self
        presenter.viewDidLoad()
    }

}
